### ISSUE TITLE
Add support for suggestions of attribute "module" in sp:include with entries from modules-file

### ISSUE THREAD

**Issue by Schleuse** [DrWursterich/lspml#5]
Given the content of `modules-file.json` is:

```json
{
    "test-module": {
        "path": "/absolute/path/to/some/test-module/src/main/webapp"
    },
    "sitekit-module": {
        "path": "/absolute/path/to/some/other/sitekit-module/src/main/webapp"
    }
}
```
It would be nice if `<sp:include>` could offer suggestions for `module`-Attribute with the entries from the module-file. In this case `test-module` & `sitekit-module`.

**Comment by DrWursterich** [comment]
Thanks for the input!
